name: asan_login_flutter
description: ASAN Login implementation for Flutter (maintained by community)
version: 1.2.0
homepage: https://github.com/cib-az/asan-login-flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.4.4+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: