name: asan_login_flutter
description: ASAN Login for Flutter
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.3.2
  rxdart: ^0.27.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: